# Generated by Django 4.1.7 on 2023-06-10 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student_Details_App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='id_number',
            field=models.AutoField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
