# Generated by Django 4.1.7 on 2023-06-10 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student_Details_App', '0002_alter_student_id_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='totalfine',
            field=models.IntegerField(default=0),
        ),
    ]
