# Generated by Django 4.0.3 on 2023-06-10 06:39

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Student_Details_App', '0001_initial'),
        ('Books_App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookLending',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_date', models.DateField(default=django.utils.timezone.now)),
                ('due_date', models.DateField()),
                ('fine', models.IntegerField(default=0)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Books_App.book')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Student_Details_App.student')),
            ],
        ),
    ]
